### ISSUE TITLE
Bug: Identify Broken Imports in Metaschema

### ISSUE THREAD

**Issue by david-waltermire** [usnistgov/metaschema-xslt#8]
# User Story:

As an OSCAL metaschema developer, I need an error to be generated when I try to import another metaschema inside a different metaschema, and the imported metaschema does not exist.

## Goals:

Report an error when importing a metaschema that doesn't exist and fail the transform.

## Dependencies:

None.

## Acceptance Criteria

- An updated transform that addresses this issue has been tested and submitted as a PR.

**Comment by wendellpiez** [comment]
I suggest at least these checks:

1. Runtime check in Metaschema compiler. This could be draconian, as in fail-to-deliver if modules do not resolve as expected (to Metaschemas), maybe even error out (`xsl:message[@terminate='yes']`. The current bug occurs because Saxon failed to find a document at a URL (not an XSLT error).
1. Also, a pre-emptive check in Metaschema Schematron that would signal an error for a missing module, with a nice explicit message.

**Comment by wendellpiez** [comment]
This should be straightforward in the context of usnistgov/metaschema#39.

**Comment by david-waltermire** [comment]
The XSLT implementation should identify that the referenced metaschema could not be resolved and exit. It looks like there is a commit to fix this. We should verify that this has been fixed in the latest metaschema composition transform.

**Comment by wendellpiez** [comment]
This could be queued up and possibly resolved in a spike.

Unit tests would also help, however. Should this be tested and resolved without unit testing Metaschema imports (in any implementation)?

**Comment by david-waltermire** [comment]
Use of [doc-available](https://www.w3.org/TR/xpath-functions-31/#func-doc-available) can be used to check if the imported resource is resolvable and can be parsed.

**Comment by wendellpiez** [comment]
Update July 2023 --

The current XSLT functionality should now have this: https://github.com/wendellpiez/metaschema-xslt/blob/18308b03d5db5b41bfead6fad2be493a0fe1adfe/src/compose/metaschema-collect.xsl#L76

A possible follow-on Issue in Metaschema repository would be is to test and demonstrate this for any implementation.
